%% TMM Verification Script for Lumerical STACK Results
% This script implements the Transfer Matrix Method (TMM) to verify
% the results generated by Lumerical for the multi-cavity system.

clear; clc; close all;

%% 1. Load Lumerical Results
csv_path = '../results/PSS_TiO2_reflection.csv'; % Change name to verify other stacks
if ~exist(csv_path, 'file')
    error('CSV result file not found. Please run main.py first.');
end
data = readtable(csv_path);
lambda_vec = data.Wavelength_nm; % nm
R_lumerical = data.Reflection;

%% 2. Simulation Parameters
lambda_um = lambda_vec / 1000;
k0 = 2 * pi ./ (lambda_vec * 1e-9);

% Material Models (Cauchy: n = A + B/lambda^2)
n_reflector = 5.8284;
n_hsq = 1.39 + 0.003 ./ (lambda_um.^2);
n_pss = (1.48 + 0.004 ./ (lambda_um.^2)) + 1i * 0.05;
n_soc = (1.55 + 0.005 ./ (lambda_um.^2)) + 1i * 0.01;
n_tio2 = 2.40 + 0.020 ./ (lambda_um.^2);
n_hfo2 = 2.00 + 0.015 ./ (lambda_um.^2);
n_air = 1.0;
n_cu = 0.2 + 1i * 3.4; % Simplified Cu index for verification, or use tabulated
n_sin = 2.0;            % Simplified SiN index

% Thicknesses (meters)
d_air = 1e-3;
d_hsq = 30e-9;
d_cond = 5e-9; % PSS or Cr
d_soc = 45e-9;
d_hm = 20e-9;  % TiO2 or HfO2
d_cu = 100e-9;

%% 3. TMM Calculation (Normal Incidence)
R_matlab = zeros(size(lambda_vec));

for i = 1:length(lambda_vec)
    % Indices for current wavelength
    % Stack: Reflector | Air | HSQ | PSS | SOC | TiO2 | Cu | SiN
    n = [n_reflector, n_air, n_hsq(i), n_pss(i), n_soc(i), n_tio2(i), n_cu, n_sin];
    d = [0, d_air, d_hsq, d_cond, d_soc, d_hm, d_cu, 0];
    
    M = eye(2);
    for j = 2:length(n)-1
        phi = n(j) * k0(i) * d(j);
        Mj = [cos(phi), -1i/n(j) * sin(phi); ...
              -1i*n(j)*sin(phi), cos(phi)];
        M = M * Mj;
    end
    
    % Reflectance calculation
    n_in = n(1);
    n_sub = n(end);
    
    m11 = M(1,1); m12 = M(1,2); m21 = M(2,1); m22 = M(2,2);
    
    r = (n_in * (m11 + n_sub * m12) - (m21 + n_sub * m22)) / ...
        (n_in * (m11 + n_sub * m12) + (m21 + n_sub * m22));
    
    R_matlab(i) = abs(r)^2;
end

%% 4. Plot Comparison
figure('Color', 'w', 'Position', [100, 100, 1000, 600]);

% Subplot 1: Broadband Comparison
subplot(2,1,1);
plot(lambda_vec, R_lumerical, 'b-', 'LineWidth', 1.5, 'DisplayName', 'Lumerical (STACK)');
hold on;
plot(lambda_vec, R_matlab, 'r--', 'LineWidth', 1.0, 'DisplayName', 'MATLAB (TMM)');
title('Broadband Reflection Comparison');
xlabel('Wavelength (nm)');
ylabel('Reflection');
legend; grid on;

% Subplot 2: Zoomed-in Detail (600nm)
subplot(2,1,2);
zoom_mask = (lambda_vec >= 599.5 & lambda_vec <= 600.5);
plot(lambda_vec(zoom_mask), R_lumerical(zoom_mask), 'b-o', 'MarkerSize', 4, 'DisplayName', 'Lumerical');
hold on;
plot(lambda_vec(zoom_mask), R_matlab(zoom_mask), 'r--x', 'MarkerSize', 4, 'DisplayName', 'MATLAB');
title('Fringe Detail Comparison (600nm Zoom)');
xlabel('Wavelength (nm)');
ylabel('Reflection');
legend; grid on;

fprintf('Verification Complete.\n');
